# Generated by Django 5.0.6 on 2024-05-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='star_givere',
        ),
    ]
