# Generated by Django 5.0.6 on 2024-05-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_foods_star_givere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='description',
        ),
    ]
