# Generated by Django 5.0.6 on 2024-05-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_foods_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='created_at',
        ),
    ]
