# Generated by Django 5.0.6 on 2024-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_foods_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
